/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import classes.Carro;
import classes.BancoDeDados;
import classes.Verificador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parac
 */

//Permite a criação, leitura, atualização e remoção de carros em sincronia com o banco de dados
public class CRUDCarros extends javax.swing.JFrame {
    
    static BancoDeDados bancoDeDados;
    private String modoAtual;
    Verificador verificador;

    /**
     * Creates new form CRUDClientes
     */

    //estado atual do programa de acordo com o botão selecionado
    private void modoPadrao(){
        modoAtual = "padrao";
        btnOk.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAdicionar.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtPlaca.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtNome.setEnabled(false);
        txtAno.setEnabled(false);
        txtCor.setEnabled(false);
        txtPreco.setEnabled(false);
        
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtNome.setText("");
        txtAno.setText("");
        txtCor.setText("");
        txtPreco.setText("");
    }
    
    private void modoAdicionar(){
        modoAtual = "adicionar";
        btnOk.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtPlaca.setEnabled(true);
        txtMarca.setEnabled(true);
        txtModelo.setEnabled(true);
        txtNome.setEnabled(true);
        txtAno.setEnabled(true);
        txtCor.setEnabled(true);
        txtPreco.setEnabled(true);
    }
    
    private void modoPesquisar(){
        modoAtual = "pesquisar";
        btnOk.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtPlaca.setEnabled(true);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtNome.setEnabled(false);
        txtAno.setEnabled(false);
        txtCor.setEnabled(false);
        txtPreco.setEnabled(false);
    }
    
    private void modoEditar(){
        modoAtual = "editar";
        btnOk.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtPlaca.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtNome.setEnabled(false);
        txtAno.setEnabled(false);
        txtCor.setEnabled(true);
        txtPreco.setEnabled(true);
    }
    
    private void modoExcluir(){
        modoAtual = "excluir";
        btnOk.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtPlaca.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtNome.setEnabled(false);
        txtAno.setEnabled(false);
        txtCor.setEnabled(false);
        txtPreco.setEnabled(false);
    }
    
    public CRUDCarros() {
        initComponents();
        bancoDeDados = Inicial.bancoDeDados;
        modoPadrao();
        atualizarTabela();
        verificador = new Verificador();
    }

    //Atualiza tabela de Carros
    private void atualizarTabela(){
        Object[] campos = {"Placa", "Marca", "Modelo", "Nome", "Ano", "Cor", "Preço"};
        DefaultTableModel modelo = new DefaultTableModel(campos,0);
        var carros = bancoDeDados.getCarros();
        for(var c : carros){
            Object[] linha = {c.getPlaca(),c.getMarca(),c.getModelo(),c.getNome(),
                String.valueOf(c.getAno()),c.getCor(),String.format("%.2f",c.getPrecoDiario())};
            modelo.addRow(linha);
        }
        tblCarros.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblPLaca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carros");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Carro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnOk.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnOk.setForeground(new java.awt.Color(0, 153, 0));
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelar.setText("X");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblPLaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPLaca.setText("Placa:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Marca:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Modelo:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Ano:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Cor:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Preço:");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblPLaca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPLaca)
                    .addComponent(jLabel5)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnPesquisar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tblCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Nome", "Modelo", "Ano", "Cor", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tblCarros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        modoAdicionar();
    }                                            

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        modoPesquisar();
    }                                            

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        modoEditar();
    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        modoExcluir();
    }                                          

    //Botão de confirmar, que age diferente de acordo com o botão apertado anteriormente
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if (modoAtual.equals("adicionar")){
            String placa = txtPlaca.getText();
            String marca = txtMarca.getText();
            String modelo = txtModelo.getText();
            String nome = txtNome.getText();
            String textoAno = txtAno.getText();
            String cor = txtCor.getText();
            String textoPreco = txtPreco.getText();
            if (adicionarCarro(placa,marca,modelo,nome,textoAno,cor,textoPreco)){
                modoPadrao();
            }
        }
        else if (modoAtual.equals("pesquisar")){
            String placa = txtPlaca.getText();
            if (mostrarCarro(placa)){
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        }
        else if (modoAtual.equals("editar")){
            String placa = txtPlaca.getText();
            String cor = txtCor.getText();
            String textoPreco = txtPreco.getText();
            if (editarCarro(placa,cor,textoPreco)){
                modoPadrao();
            }
        }
        else if (modoAtual.equals("excluir")){
            String placa = txtPlaca.getText();
            excluirCarro(placa);
            modoPadrao();
        }
    }                                     
    
    private boolean adicionarCarro(String placa, String marca, String modelo, String nome, String textoAno, String cor, String textoPreco){
        String erros = "\n";
        if (!verificador.isPlaca(placa)){
            erros = erros + "\nPlaca inválida.";
        }
        if (!verificador.isMarca(marca)){
            erros = erros + "\nMarca inválida.";
        }
        if (!verificador.isModelo(modelo)){
            erros = erros + "\nModelo inválido.";
        }
        if (!verificador.isNome(nome)){
            erros = erros + "\nNome não pode ser nulo.";
        }
        if (!verificador.isCor(cor)){
            erros = erros + "\nCor não pode ser nula.";
        }
        if (!verificador.isAno(textoAno)){
            erros = erros + "\nAno inválido.";
        }
        if (!verificador.isPreco(textoPreco)){
            erros = erros + "\nPreço deve ser um valor positivo de ponto flutuante.";
        }
        if (!erros.equals("\n")){
            JOptionPane.showMessageDialog(null, "Erro no preenchimento:"+erros, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        short ano = Short.parseShort(textoAno);
        double preco = Double.parseDouble(textoPreco.replace(",","."));
        Carro carro = new Carro(marca,placa,ano,nome,modelo,cor,preco);
        bancoDeDados.adicionar(carro);
        atualizarTabela();
        JOptionPane.showMessageDialog(null, "Carro adicionado com sucesso", "Concluído", JOptionPane.PLAIN_MESSAGE);
        return true;
    }
    
    private boolean editarCarro(String placa, String cor, String textoPreco){
        String erros = "\n";
        if (!verificador.isCor(cor)){
            erros = erros + "Cor não pode ser nula.";
        }
        if (!verificador.isPreco(textoPreco)){
            erros = erros + "Preço deve ser valor positivo de ponto flutuante.";
        }
        if (!erros.equals("\n")){
            JOptionPane.showMessageDialog(null, "Erro nos campos:"+erros, "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        double preco = Double.parseDouble(textoPreco.replace(",","."));
        var carros = bancoDeDados.getCarros();
        for(var c : carros){
            if (c.getPlaca().equals(placa)){
                c.setCor(cor);
                c.setPrecoDiario(preco);
                bancoDeDados.editar(c);
                break;
            }
        }
        atualizarTabela();
        JOptionPane.showMessageDialog(null, "Carro editado com sucesso", "Concluído", JOptionPane.PLAIN_MESSAGE);
        return true;
    }
    
    private boolean mostrarCarro(String placa){
        Carro carro = null;
        var carros = bancoDeDados.getCarros();
        for(var c : carros){
            if (c.getPlaca().equals(placa)){
                carro = c;
            }
        }
        if (carro == null){
            JOptionPane.showMessageDialog(null, "Carro não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            txtPlaca.setText(carro.getPlaca());
            txtMarca.setText(carro.getMarca());
            txtModelo.setText(carro.getModelo());
            txtNome.setText(carro.getNome());
            txtAno.setText(String.valueOf(carro.getAno()));
            txtCor.setText(carro.getCor());
            txtPreco.setText(String.format("%.2f",carro.getPrecoDiario()));
            JOptionPane.showMessageDialog(null, "Carro pronto para edição/exclusão", "Concluído", JOptionPane.PLAIN_MESSAGE);
            return true;
        }
    }
    
    private void excluirCarro(String placa){
        Carro carro = null;
        var carros = bancoDeDados.getCarros();
        for(var c : carros){
            if (c.getPlaca().equals(placa)){
                carro = c;
            }
        }
        bancoDeDados.apagar(carro);
        atualizarTabela();
        JOptionPane.showMessageDialog(null, "Carro excluído permanentemente", "Concluído", JOptionPane.PLAIN_MESSAGE);
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        modoPadrao();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPLaca;
    private javax.swing.JTable tblCarros;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration                   
}
