/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Carro;
import classes.Cliente;
import classes.Funcionario;
import classes.BancoDeDados;
import classes.SessaoUsuario;
import classes.Verificador;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author parac
 */
public class TelaAluguel extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluguel
     */
    
    static Funcionario funcionarioSelecionado;
    static Cliente clienteSelecionado;
    static Carro carroSelecionado;
    static BancoDeDados bancoDeDados;
    static LocalDate dataInicioAluguel;
    static LocalDate dataFimAluguel;
    Verificador verificador;
    
    public TelaAluguel() {
        initComponents();
        bancoDeDados = Inicial.bancoDeDados;
        funcionarioSelecionado = SessaoUsuario.getInstancia().getUsuarioLogado();
        verificador = new Verificador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        selecaoData = new javax.swing.JPanel();
        lblDiaInicial = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDiaFinal = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        bntPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblMarca1 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblDiaFinal2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblDiaFinal1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnAlugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aluguel");

        lblDiaInicial.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDiaInicial.setText("Data inicial:");

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTitulo.setText("Selecione a data para aluguel:");

        lblDiaFinal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDiaFinal.setText("Data final:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        lblMarca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMarca.setText("Marca do Carro:");

        bntPesquisar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bntPesquisar.setText("Pesquisar");
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 300));

        jTable1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Marca", "Nome", "Modelo", "Ano", "Cor", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblMarca1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMarca1.setText("Preço Máximo:");

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        lblDiaFinal2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDiaFinal2.setText("CPF cliente:");

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        lblDiaFinal1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDiaFinal1.setText("Placa:");

        javax.swing.GroupLayout selecaoDataLayout = new javax.swing.GroupLayout(selecaoData);
        selecaoData.setLayout(selecaoDataLayout);
        selecaoDataLayout.setHorizontalGroup(
            selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoDataLayout.createSequentialGroup()
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(selecaoDataLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo)
                        .addGap(0, 612, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(selecaoDataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selecaoDataLayout.createSequentialGroup()
                        .addComponent(lblDiaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(lblDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(selecaoDataLayout.createSequentialGroup()
                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(lblMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(selecaoDataLayout.createSequentialGroup()
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selecaoDataLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(bntPesquisar))
                    .addGroup(selecaoDataLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblDiaFinal2)
                        .addGap(37, 37, 37)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(lblDiaFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selecaoDataLayout.setVerticalGroup(
            selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecaoDataLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca1)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(bntPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(selecaoDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnAlugar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAlugar.setText("Alugar");
        btnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selecaoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(btnAlugar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(selecaoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAlugar)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        Date dataInicioDate = (Date) jDateChooser1.getDate();
        Date dataFimDate = (Date) jDateChooser2.getDate();

        if (dataInicioDate == null || dataFimDate == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione as datas de início e fim.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate dataInicio = dataInicioDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dataFim = dataFimDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if (dataInicio.isAfter(dataFim)){
            JOptionPane.showMessageDialog(this, "Data inicial deve vir antes da final.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LocalDate atual = LocalDate.now();
        if (dataInicio.isBefore(atual)){
            JOptionPane.showMessageDialog(this, "Data inicial não pode ser anterior à atual.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String marca = jTextField1.getText().trim();
        String precoMaximo = txtPreco.getText().trim();
        double preco = -1.0;

        if (!marca.isEmpty() && !verificador.isMarca(marca)) {
            JOptionPane.showMessageDialog(this, "Marca Inválida", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (!precoMaximo.isEmpty() && !verificador.isPreco(precoMaximo)){
            JOptionPane.showMessageDialog(this, "Preço Inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            if (!precoMaximo.isEmpty())preco = Double.parseDouble(precoMaximo.replace(',', '.'));
        }

        // Realiza a busca dos carros disponíveis
        ArrayList<Carro> carros = bancoDeDados.getCarros();
        ArrayList<Carro> carrosDisponiveis = new ArrayList<>();

        for (Carro carro : carros) {
            if (!marca.isEmpty() && !carro.getMarca().equalsIgnoreCase(marca))continue;
            if (!precoMaximo.isEmpty() && carro.getPrecoDiario() > preco)continue;
            if (carro.disponivelEntre(dataInicio, dataFim))carrosDisponiveis.add(carro);
        }

        // Atualiza a tabela com os carros disponíveis
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0); // Limpa a tabela

        for (Carro carro : carrosDisponiveis) {
            Object[] rowData = {
                carro.getPlaca(),
                carro.getMarca(),
                carro.getNome(),
                carro.getModelo(),
                String.valueOf(carro.getAno()),
                carro.getCor(),
                String.format("%.2f",carro.getPrecoDiario())
            };
            tableModel.addRow(rowData);
        }
    }//GEN-LAST:event_bntPesquisarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarActionPerformed
        Date dataInicioDate = (Date) jDateChooser1.getDate();
        Date dataFimDate = (Date) jDateChooser2.getDate();

        if (dataInicioDate == null || dataFimDate == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione as datas de início e fim.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate dataInicio = dataInicioDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dataFim = dataFimDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if (dataInicio.isAfter(dataFim)){
            JOptionPane.showMessageDialog(this, "Data inicial deve vir antes da final.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        LocalDate atual = LocalDate.now();
        if (dataInicio.isBefore(atual)){
            JOptionPane.showMessageDialog(this, "Data inicial não pode ser anterior à atual.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String cpf = txtCpf.getText();
        String placa = txtPlaca.getText();
        if (!verificador.isCpf(cpf) || !verificador.isPlaca(placa)){
            JOptionPane.showMessageDialog(null, "CPF ou Placa inválidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            carroSelecionado = bancoDeDados.getCarro(placa);
            clienteSelecionado = bancoDeDados.getCliente(cpf);
            dataInicioAluguel = dataInicio;
            dataFimAluguel = dataFim;
            new ConfirmacaoAluguel().setVisible(true);
            //JOptionPane.showMessageDialog(null, "OK "+placa+" "+cpf, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAlugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton btnAlugar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDiaFinal;
    private javax.swing.JLabel lblDiaFinal1;
    private javax.swing.JLabel lblDiaFinal2;
    private javax.swing.JLabel lblDiaInicial;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel selecaoData;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
